version: "3.8"

services:
  bannerAIDb:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bannerDb
      DB_HOST: bannerAIDb

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  banner-ai-server:
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - bannerAIDb
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
