services:
  bannerAIDb:
    image: postgres:14
    hostname: bannerAIDb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bannerDb
